import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import Header from "../components/Header/Header";
import HomeModule from "../containers/HomeModule/HomeModule";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeModule />
    </div>
  );
};

export default Home;
